const user = {
    "login": "Bello2288",
    "id": 112423421,
    "node_id": "U_kgDOBrNx_Q",
    "avatar_url": "https://avatars.githubusercontent.com/u/112423421?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Bello2288",
    "html_url": "https://github.com/Bello2288",
    "followers_url": "https://api.github.com/users/Bello2288/followers",
    "following_url": "https://api.github.com/users/Bello2288/following{/other_user}",
    "gists_url": "https://api.github.com/users/Bello2288/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Bello2288/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Bello2288/subscriptions",
    "organizations_url": "https://api.github.com/users/Bello2288/orgs",
    "repos_url": "https://api.github.com/users/Bello2288/repos",
    "events_url": "https://api.github.com/users/Bello2288/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Bello2288/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Gregg Bellofatto",
    "company": "Carolina Code School",
    "blog": "",
    "location": "Greenville, SC",
    "email": null,
    "hireable": null,
    "bio": null,
    "twitter_username": null,
    "public_repos": 10,
    "public_gists": 0,
    "followers": 0,
    "following": 0,
    "created_at": "2022-08-29T18:04:25Z",
    "updated_at": "2022-09-21T00:18:22Z"
  }

  export default user;